root: true
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
  - "plugin:prettier/recommended"
rules:
  prettier/prettier:
    - "error"
    -
      trailingComma: all
      bracketSpacing: true
      singleQuote: true
      useTabs: false
      semi: true
      endOfLine: auto
      printWidth: 100
      tabWidth: 2

